services:
 server:
  container_name: afoodable-server
  build:
   context: ./
   dockerfile: ./Server/Dockerfile
  ports: 
   - 9998:9998
  networks:
   afoodable:
    ipv4_address: 192.168.11.6

 client:
  container_name: afoodable-client
  build:
   context: ./
   dockerfile: ./Client/Dockerfile
  ports:
   - 9999:9999
  networks:
   afoodable:
    ipv4_address: 192.168.11.5

networks:
  afoodable:
    ipam:
      driver: default
      config:
        - subnet: "192.168.11.0/24"
        - subnet: "2001:3984:3989::/64"